# Generated by Django 5.2.3 on 2025-06-11 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 25, 9, 29, 20, 166690, tzinfo=datetime.timezone.utc)),
        ),
    ]
