# Generated by Django 5.2.3 on 2025-06-11 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_bookissue_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 25, 9, 51, 30, 587582, tzinfo=datetime.timezone.utc)),
        ),
    ]
