# Generated by Django 5.2.3 on 2025-06-11 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_bookissue_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 25, 11, 7, 12, 702768, tzinfo=datetime.timezone.utc)),
        ),
    ]
