# Generated by Django 5.2.3 on 2025-06-12 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_bookissue_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 26, 13, 53, 44, 329538, tzinfo=datetime.timezone.utc)),
        ),
    ]
