# Generated by Django 5.2.3 on 2025-06-13 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_bookissue_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 27, 7, 50, 51, 186460, tzinfo=datetime.timezone.utc)),
        ),
    ]
