# Generated by Django 5.2.2 on 2025-06-14 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_bookissue_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='returned_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 28, 9, 19, 57, 944953, tzinfo=datetime.timezone.utc)),
        ),
    ]
