# Generated by Django 5.2.3 on 2025-06-16 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_bookissue_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='damaged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 30, 6, 5, 35, 81700, tzinfo=datetime.timezone.utc)),
        ),
    ]
