# Generated by Django 5.2.3 on 2025-06-16 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_damaged_alter_bookissue_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='damaged',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 30, 6, 8, 23, 164514, tzinfo=datetime.timezone.utc)),
        ),
    ]
