# Generated by Django 5.2.3 on 2025-06-24 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_book_damaged_alter_bookissue_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 7, 8, 5, 7, 2, 653096, tzinfo=datetime.timezone.utc)),
        ),
    ]
