# Generated by Django 5.2.3 on 2025-06-24 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_bookissue_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='return_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 7, 8, 5, 23, 31, 478352, tzinfo=datetime.timezone.utc)),
        ),
    ]
