# Generated by Django 5.2.3 on 2025-06-26 06:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_bookissue_return_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 7, 10, 6, 46, 45, 891897, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='BookReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.bookissue')),
            ],
        ),
    ]
